POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "aslas",
  "apellidoPaterno": "aslasito",
  "apellidoMaterno": "Alarcón",
  "telefono": "555-1234",
  "email": "juan.perez@example.com",
  "password": "securePassword123",
  "direccion": "Calle Falsa 123, Ciudad",
  "rol": "usuario",
  "fechaRegistro": "2023-09-15",
  "especialidad": "no"
}